FROM python:3.10-slim

WORKDIR /app

COPY app/ ./app
COPY templates/ ./templates
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=app/app.py

CMD ["python", "app/app.py"]
